version: "3"
services:
  e2e:
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    build: 
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - web
    command: npm run test-e2e
    environment:
      DATABASE_URL: postgres://postgres:pgpassword@db:5432/todos
  web:
    build: .
    command: node app/app.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:pgpassword@db:5432/todos
  db:
    image: postgres:11.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=todos
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql