version: "3"
services:
  webapp:
    build: .
    command: node app/app.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - pgdatabase
    environment:
      DATABASE_URL: postgres://postgres:pgpassword@pgdatabase:5432/todos
  pgdatabase:
    image: postgres:11.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=todos
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sql
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql